environment:
  matrix:
  - nodejs_version: "14"
install:
  - npm
test_script:
  - npm test
build: off

before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb testdb
services:
  - postgresql101